version: 2.1
           
jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
              cd frontend
              sudo apt-get install npm
              npm run build

  build-backend:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
              cd backend
              sudo apt-get install npm
              npm run build
             

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend